### ISSUE TITLE
This is not an issue but can not find somewhere else to ask

### ISSUE THREAD

**Issue by temizermerve** [COMSYS/FootPath#2]
I have generated a new OSM file

But even i tried every way to make it look like your original osm files i could not achieve to run project in eclipse with my new generated OSM.

https://www.dropbox.com/s/qkpwub75fejepty/line.osm?dl=0

**Comment by temizermerve** [comment]
my int values are too big

but i think this is a bug

**Comment by Yibinnn** [comment]
I can't find the file : "de.uvwxy.footpath.Rev"

**Comment by AI4Medicine-SJTU** [comment]
yeah, I can't find the file : "de.uvwxy.footpath.Rev" . this project is pretty good. But this bug makes me confused.

**Comment by jo-bitsch** [comment]
When you run the [update-revfile.sh](https://github.com/COMSYS/FootPath/blob/master/update-revfile.sh) file, this will create the missing file for you. This helps to keep track of which git revision created data.

Alternatively, you can just add a file `/de/uvwxy/footpath/Rev.java` with the following content:
`package de.uvwxy.footpath;public class Rev{public final static String rev = "no ref";}`

**Comment by jo-bitsch** [comment]
This project is no longer actively maintained for quite some time, as it was only a research prototype.

However, if anyone wants to:

1. Create a pull request, or 
2. Fork

you are very welcome to do so, keeping in mind the conditions of [GPLv3+](https://github.com/COMSYS/FootPath/blob/master/LICENSE.txt)
