### ISSUE TITLE
[Not an issue] A question regarding use areas of FootPath

### ISSUE THREAD

**Issue by mustafa-yilmaz-zz** [COMSYS/FootPath#3]
Since I could not find any other appropriate channel, I had to ask my question here.

Could one provide (submit) his/her location as global coordinates to a system through FootPath while (s)he is inside a building? In my case, there is no need for much precision (accuracy), no need to know in which part of the building the user is, the exact accuracy level needed is determining in which building the user is. Could FootPath be used for such an aim?

Thanks very much in advance for any response.

Regards,

Mustafa

**Comment by uvwxy** [comment]
Footpath relies on the user's input to start the position tracking. This means without an initial position the algorithm can not provide a location.

If I understood your question correctly, the answer would be no.
