### ISSUE TITLE
Android Studio import fails

### ISSUE THREAD

**Issue by akarsh** [COMSYS/FootPath#4]
I tried to contribute this project by adding iD viewer.
But the project import fails in android studio.

**Comment by uvwxy** [comment]
What is "iD viewer"?

I imported the project to Android Studio, if you disable the lint errors, you should be able to run it.

**Comment by akarsh** [comment]
Hi @uvwxy 
Regarding  [iD viewer](http://learnosm.org/en/beginner/id-editor/)

In the android studio for the osm files in the xml folder. was throwing error for me.

**Comment by uvwxy** [comment]
Checkout the `develop` branch on [uvwxy/FootPath](https://github.com/uvwxy/FootPath).

I moved the xml files to `src/main/assets/` and change the way they are loaded. Still the Application does not run properly yet.
