### ISSUE TITLE
Adding maps to application

### ISSUE THREAD

**Issue by akarsh** [COMSYS/FootPath#5]
The gradle project issue solved.
But how to add indoor maps to the application to see if it is working.
I noticed that the osm file extension has been renamed as xml.

Does changing the file extension has any impact on precision of the map ?

![device-2017-04-26-091603](https://cloud.githubusercontent.com/assets/845598/25422467/415fe636-2a61-11e7-85b2-7a75029bd684.png)

![device-2017-04-26-091551](https://cloud.githubusercontent.com/assets/845598/25422466/411ee366-2a61-11e7-8140-0121404bafb9.png)

**Comment by uvwxy** [comment]
The file extension has no impact on the code that handles loading the map.

You can add additional xml/osm files (with the right indoor path annotations) to the external storage.

**Comment by uvwxy** [comment]
Please git clone the updated repository: [github.com/uvwxy/FootPath](https://github.com/uvwxy/FootPath)
If you open this with Android Studio you should be able to repeat the steps shown in the video:
https://www.youtube.com/watch?v=XI09uTy8gjE&feature=youtu.be
